#!/bin/bash
# Modified by PastureStack contributors for independent maintenance and rebranding.
set -euo pipefail

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
CGO_ENABLED=0 go build -trimpath -ldflags "-buildid= -X main.Version=$VERSION -s -w" -o bin/external-dns-sync
