#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

echo Running: go vet
go vet -mod=vendor ./...
#echo Running: golint
#for i in ${PACKAGES}; do
#    if [ -n "$(golint $i | grep -v 'should have comment.*or be unexported' | tee /dev/stderr)" ]; then
#        failed=true
#    fi
#done
#test -z "$failed"
#echo Running: go fmt
#test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
